return {
  'folke/which-key.nvim',
  event = 'VimEnter',
  opts = {
    delay = 0,
    icons = {
      mappings = vim.g.have_nerd_font,
      keys = vim.g.have_nerd_font and {} or {
        Up = '<Up> ',
        Down = '<Down> ',
        Left = '<Left> ',
        Right = '<Right> ',
        C = '<C-…> ',
        M = '<M-…> ',
        D = '<D-…> ',
        S = '<S-…> ',
        CR = '<CR> ',
        Esc = '<Esc> ',
        ScrollWheelDown = '<ScrollWheelDown> ',
        ScrollWheelUp = '<ScrollWheelUp> ',
        NL = '<NL> ',
        BS = '<BS> ',
        Space = '<Space> ',
        Tab = '<Tab> ',
        F1 = '<F1>',
        F2 = '<F2>',
        F3 = '<F3>',
        F4 = '<F4>',
        F5 = '<F5>',
        F6 = '<F6>',
        F7 = '<F7>',
        F8 = '<F8>',
        F9 = '<F9>',
        F10 = '<F10>',
        F11 = '<F11>',
        F12 = '<F12>',
      },
    },

    spec = {
      { '<leader>s', group = '[S]earch' },
      { '<leader>t', group = '[T]oggle' },
      { '<leader>ts', '<cmd>lua require("neotest").summary.toggle()<cr>', desc = '[T]oggle Test [S]ummary' },
      { '<leader>n', group = 'Ru[N]' },
      { '<leader>nn', '<cmd>lua require("neotest").run.run()<cr>', desc = 'Ru[N] [N]earest Test' },
      { '<leader>na', '<cmd>lua require("neotest").run.run({suite = true })<cr>', desc = 'Ru[N] [A]ll Tests' },
      { '<leader>nf', '<cmd>lua require("neotest").run.run(vim.fn.expand("%"))<cr>', desc = 'Ru[N] Tests in Current [F]ile' },
      { '<leader>h', group = 'Git [H]unk', mode = { 'n', 'v' } },
      { '<leader>g', group = '[G]o To', mode = { 'n', 'v' } },
      { '<leader>r', group = '[R]ename', mode = { 'n', 'v' } },
      { '<leader>d', group = '[D]ebug', mode = { 'n' } },
    },
  },
}
